# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ethan/xwg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ethan/xwg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ethan/xwg/CMakeFiles /home/ethan/xwg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ethan/xwg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main-obj

# Build rule for target.
main-obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main-obj
.PHONY : main-obj

# fast build rule for target.
main-obj/fast:
	$(MAKE) -f CMakeFiles/main-obj.dir/build.make CMakeFiles/main-obj.dir/build
.PHONY : main-obj/fast

#=============================================================================
# Target rules for targets named xwg

# Build rule for target.
xwg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xwg
.PHONY : xwg

# fast build rule for target.
xwg/fast:
	$(MAKE) -f CMakeFiles/xwg.dir/build.make CMakeFiles/xwg.dir/build
.PHONY : xwg/fast

#=============================================================================
# Target rules for targets named a1-obj

# Build rule for target.
a1-obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a1-obj
.PHONY : a1-obj

# fast build rule for target.
a1-obj/fast:
	$(MAKE) -f CMakeFiles/a1-obj.dir/build.make CMakeFiles/a1-obj.dir/build
.PHONY : a1-obj/fast

a1.o: a1.cpp.o

.PHONY : a1.o

# target to build an object file
a1.cpp.o:
	$(MAKE) -f CMakeFiles/a1-obj.dir/build.make CMakeFiles/a1-obj.dir/a1.cpp.o
.PHONY : a1.cpp.o

a1.i: a1.cpp.i

.PHONY : a1.i

# target to preprocess a source file
a1.cpp.i:
	$(MAKE) -f CMakeFiles/a1-obj.dir/build.make CMakeFiles/a1-obj.dir/a1.cpp.i
.PHONY : a1.cpp.i

a1.s: a1.cpp.s

.PHONY : a1.s

# target to generate assembly for a file
a1.cpp.s:
	$(MAKE) -f CMakeFiles/a1-obj.dir/build.make CMakeFiles/a1-obj.dir/a1.cpp.s
.PHONY : a1.cpp.s

xor-new.o: xor-new.cpp.o

.PHONY : xor-new.o

# target to build an object file
xor-new.cpp.o:
	$(MAKE) -f CMakeFiles/main-obj.dir/build.make CMakeFiles/main-obj.dir/xor-new.cpp.o
.PHONY : xor-new.cpp.o

xor-new.i: xor-new.cpp.i

.PHONY : xor-new.i

# target to preprocess a source file
xor-new.cpp.i:
	$(MAKE) -f CMakeFiles/main-obj.dir/build.make CMakeFiles/main-obj.dir/xor-new.cpp.i
.PHONY : xor-new.cpp.i

xor-new.s: xor-new.cpp.s

.PHONY : xor-new.s

# target to generate assembly for a file
xor-new.cpp.s:
	$(MAKE) -f CMakeFiles/main-obj.dir/build.make CMakeFiles/main-obj.dir/xor-new.cpp.s
.PHONY : xor-new.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main-obj"
	@echo "... xwg"
	@echo "... a1-obj"
	@echo "... rebuild_cache"
	@echo "... a1.o"
	@echo "... a1.i"
	@echo "... a1.s"
	@echo "... xor-new.o"
	@echo "... xor-new.i"
	@echo "... xor-new.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

